version: 2

models:
  - name: stg_customers
    tests:
      - unique:
          column_name: customer_id
      - not_null:
          column_name: customer_id

  - name: stg_orders
    tests:
      - unique:
          column_name: order_id
      - not_null:
          column_name: order_id
      - relationships:            # FK check
          to: ref('stg_customers')
          field: customer_id
          column_name: customer_id